# Site settings

title: Paul Wang # Title of your site
email: paul_wang347@hotmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for Paul Wang
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pwang347.github.io/" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

resume_name: resume-for-coop.pdf  
github_username:      pwang347
linkedin_username:    
google_plus_username: 
facebook_username:    
dribbble_username:    

# Build settings
markdown: kramdown
